# Dependencies
# This directory contains all the third-party libraries downloaded by npm.
# It can be very large and should always be regenerated by running `npm install`.
node_modules/

# Build output
# These directories contain the compiled and optimized code for production.
# They are generated by the `npm run build` command.
dist/
dist-backend/

# Logs
# These files contain debugging information and can grow very large.
npm-debug.log*
yarn-debug.log*
yarn-error.log*
# Local database
# Ignores all SQLite database files to prevent committing your local test data.
# Your production server will have its own database file.
*.db
*.db-journal

# Environment variables
# These files contain sensitive information like API keys and secrets.
# A template file (e.g., .env.example) should be committed instead.
.env
.env.*
!.env.example

# OS-generated files
.DS_Store
Thumbs.db

# IDE configuration
.vscode/
.idea/