version: '3.8'

services:
  app:
    image: mckayc/task-donegeon:latest
    container_name: task-donegeon-app-prod
    restart: unless-stopped
    ports:
      - "3002:3001"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/backend/uploads

  db:
    image: postgres:15
    container_name: task-donegeon-db-prod
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-taskdonegeon}
      POSTGRES_USER: ${POSTGRES_USER:-donegeon_master}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?You must provide a password for the database in the .env file}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-donegeon_master} -d ${POSTGRES_DB:-taskdonegeon}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: