version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      # This connects the app container to the db container.
      # The values come from the 'db' service and the .env file.
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy # Waits for the database to be ready
    networks:
      - donegeon_network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      # These values MUST match what's in your .env file
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - donegeon_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose db port to host machine for easier debugging if needed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - donegeon_network

networks:
  donegeon_network:

volumes:
  donegeon_db_data: # This persists your database data even if the container is removed