version: '3.8'

services:
  app:
    build: .
    image: mckayc/task-donegeon:latest
    container_name: task-donegeon
    restart: unless-stopped
    ports:
      # Maps your host machine's port to the container's port 3000,
      # where the backend server is running.
      - "${APP_PORT:-9373}:3000"
    environment:
      # The JWT_SECRET is now used by the backend to sign security tokens.
      # It uses the .env variable, or falls back to the insecure default.
      - JWT_SECRET=${JWT_SECRET:-insecure_default_secret_for_testing_only}
    volumes:
      # Persists application data to your host machine.
      # Defaults to a 'data' folder in the current directory.
      - "${APP_DATA_PATH:-./data}/database:/app/backend/prisma"
      - "${APP_DATA_PATH:-./data}/assets:/app/assets"
      - "${APP_DATA_PATH:-./data}/backups:/app/backups"     