services:
  app:
    image: mckayc/task-donegeon:latest
    ports:
      - "3002:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NODE_ENV=${NODE_ENV}
      - API_KEY=${API_KEY}
      - STORAGE_PROVIDER=${STORAGE_PROVIDER}
    networks:
      - donegeon_network
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - donegeon_network

volumes:
  postgres_data:

networks:
  donegeon_network:
    driver: bridge