// This file is a JavaScript adaptation of the necessary initial data from the frontend's `initialData.ts`.
// It ensures the backend can correctly initialize the app on the very first run.

const INITIAL_MAIN_SIDEBAR_CONFIG = [
    { type: 'link', id: 'Dashboard', emoji: '🏠', isVisible: true, level: 0, role: 'Explorer', termKey: 'link_dashboard' },
    { type: 'link', id: 'Quests', emoji: '🗺️', isVisible: true, level: 0, role: 'Explorer', termKey: 'link_quests' },
    { type: 'link', id: 'Calendar', emoji: '🗓️', isVisible: true, level: 0, role: 'Explorer', termKey: 'link_calendar' },
    { type: 'link', id: 'Marketplace', emoji: '💰', isVisible: true, level: 0, role: 'Explorer', termKey: 'link_marketplace' },
    { type: 'header', id: 'header-character', title: 'Explorer', emoji: '🧑‍🚀', level: 0, role: 'Explorer', isVisible: true },
    { type: 'link', id: 'Chronicles', emoji: '📜', isVisible: true, level: 1, role: 'Explorer', termKey: 'link_chronicles' },
    { type: 'link', id: 'Guild', emoji: '🏰', isVisible: true, level: 1, role: 'Explorer', termKey: 'link_guild' },
    { type: 'link', id: 'Progress', emoji: '📊', isVisible: true, level: 1, role: 'Explorer', termKey: 'link_progress' },
    { type: 'link', id: 'Avatar', emoji: '🧑‍🎤', isVisible: true, level: 1, role: 'Explorer', termKey: 'link_avatar' },
    { type: 'link', id: 'Ranks', emoji: '🎖️', isVisible: true, level: 1, role: 'Explorer', termKey: 'link_ranks' },
    { type: 'link', id: 'Collection', emoji: '🎒', isVisible: true, level: 1, role: 'Explorer', termKey: 'link_collection' },
    { type: 'link', id: 'Trophies', emoji: '🏆', isVisible: true, level: 1, role: 'Explorer', termKey: 'link_trophies' },
    { type: 'link', id: 'Themes', emoji: '🎨', isVisible: true, level: 1, role: 'Explorer', termKey: 'link_themes' },
    { type: 'header', id: 'header-admin-community', title: 'User Management', emoji: '🛡️', level: 0, role: 'Gatekeeper', isVisible: true },
    { type: 'link', id: 'Approvals', emoji: '✅', isVisible: true, level: 1, role: 'Gatekeeper', termKey: 'link_approvals' },
    { type: 'link', id: 'Manage Users', emoji: '👥', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_manage_users' },
    { type: 'link', id: 'Manage Guilds', emoji: '🏰', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_manage_guilds' },
    { type: 'header', id: 'header-admin-content', title: 'Content Management', emoji: '📚', level: 0, role: 'Donegeon Master', isVisible: true },
    { type: 'link', id: 'Manage Quests', emoji: '📜', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_manage_quests' },
    { type: 'link', id: 'Manage Quest Groups', emoji: '📂', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_manage_quest_groups' },
    { type: 'link', id: 'Manage Markets', emoji: '🛒', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_manage_markets' },
    { type: 'link', id: 'Manage Goods', emoji: '⚔️', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_manage_items' },
    { type: 'link', id: 'Manage Trophies', emoji: '🏆', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_manage_trophies' },
    { type: 'link', id: 'Manage Ranks', emoji: '🏅', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_manage_ranks' },
    { type: 'link', id: 'Manage Rewards', emoji: '💎', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_manage_rewards' },
    { type: 'link', id: 'Manage Events', emoji: '🎉', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_manage_events' },
    { type: 'link', id: 'Theme Editor', emoji: '🎭', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_theme_editor' },
    { type: 'header', id: 'header-admin-system', title: 'System Tools', emoji: '🛠️', level: 0, role: 'Donegeon Master', isVisible: true },
    { type: 'link', id: 'Asset Manager', emoji: '🖼️', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_asset_manager' },
    { type: 'link', id: 'Backup & Import', emoji: '💾', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_backup_import' },
    { type: 'link', id: 'Object Exporter', emoji: '🗂️', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_object_exporter' },
    { type: 'link', id: 'Appearance', emoji: '🖌️', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_appearance' },
    { type: 'link', id: 'Asset Library', emoji: '📚', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_asset_library' },
    { type: 'link', id: 'AI Studio', emoji: '✨', isVisible: true, level: 1, role: 'Donegeon Master', termKey: 'link_ai_studio' },
    { type: 'separator', id: 'sep-system-settings', level: 0, role: 'Donegeon Master', isVisible: true },
    { type: 'link', id: 'Settings', emoji: '⚙️', isVisible: true, level: 0, role: 'Donegeon Master', termKey: 'link_settings' },
    { type: 'separator', id: 'sep-settings-chat', level: 0, role: 'Explorer', isVisible: true },
    { type: 'link', id: 'Chat', emoji: '💬', isVisible: true, level: 0, role: 'Explorer', termKey: 'link_chat' },
    { type: 'header', id: 'header-help', title: 'Help', emoji: '❓', level: 0, role: 'Explorer', isVisible: true },
    { type: 'link', id: 'Help Guide', emoji: '❓', isVisible: true, level: 1, role: 'Explorer', termKey: 'link_help_guide' },
    { type: 'link', id: 'About', emoji: 'ℹ️', isVisible: true, level: 1, role: 'Explorer', termKey: 'link_about' },
];

const INITIAL_SETTINGS = {
    contentVersion: 0,
    favicon: '🏰',
    forgivingSetbacks: true,
    questDefaults: {
        requiresApproval: false,
        isOptional: false,
        isActive: true,
    },
    security: {
      requirePinForUsers: true,
      requirePasswordForAdmin: true,
      allowProfileEditing: true,
    },
    sharedMode: {
        enabled: false,
        quickUserSwitchingEnabled: true,
        allowCompletion: false,
        autoExit: false,
        autoExitMinutes: 2,
        userIds: [],
    },
    automatedBackups: {
        enabled: false,
        frequencyHours: 24,
        maxBackups: 7,
    },
    loginNotifications: {
        enabled: true,
    },
    theme: 'emerald',
    terminology: {
      appName: 'Task Donegeon',
      task: 'Quest', tasks: 'Quests',
      recurringTask: 'Duty', recurringTasks: 'Duties',
      singleTask: 'Venture', singleTasks: 'Ventures',
      shoppingCenter: 'Marketplace', store: 'Market', stores: 'Markets',
      history: 'Chronicles',
      group: 'Guild', groups: 'Guilds',
      level: 'Rank', levels: 'Ranks',
      award: 'Trophy', awards: 'Trophies',
      point: 'Reward', points: 'Rewards',
      xp: 'XP', currency: 'Currency',
      negativePoint: 'Setback', negativePoints: 'Setbacks',
      admin: 'Donegeon Master', moderator: 'Gatekeeper', user: 'Explorer',
      link_dashboard: 'Dashboard', link_quests: 'Quests', link_marketplace: 'Marketplace',
      link_calendar: 'Calendar', link_avatar: 'Avatar', link_collection: 'Collection',
      link_themes: 'Themes', link_guild: 'Guild', link_progress: 'Progress',
      link_trophies: 'Trophies', link_ranks: 'Ranks', link_chronicles: 'Chronicles',
      link_manage_quests: 'Manage Quests', link_manage_quest_groups: 'Manage Quest Groups',
      link_manage_items: 'Manage Goods', link_manage_markets: 'Manage Markets',
      link_manage_rewards: 'Manage Rewards', link_manage_ranks: 'Manage Ranks',
      link_manage_trophies: 'Manage Trophies', link_manage_events: 'Manage Events',
      link_theme_editor: 'Theme Editor', link_approvals: 'Approvals',
      link_manage_users: 'Manage Users', link_manage_guilds: 'Manage Guilds',
      link_ai_studio: 'AI Studio', link_appearance: 'Appearance',
      link_object_exporter: 'Object Exporter', link_asset_manager: 'Asset Manager',
      link_backup_import: 'Backup & Import', link_asset_library: 'Asset Library',
      link_settings: 'Settings', link_about: 'About', link_help_guide: 'Help Guide',
      link_chat: 'Chat',
    },
    enableAiFeatures: false,
    rewardValuation: {
      enabled: true,
      anchorRewardId: 'core-gold',
      exchangeRates: {
        'core-gems': 0.1, 'core-crystal': 20, 'core-strength': 10, 'core-diligence': 10,
        'core-wisdom': 5, 'core-skill': 5, 'core-creative': 5,
      },
      currencyExchangeFeePercent: 5,
      xpExchangeFeePercent: 10,
    },
    chat: {
        enabled: true,
        chatEmoji: '💬',
    },
    sidebars: {
        main: INITIAL_MAIN_SIDEBAR_CONFIG,
        dataManagement: [
            { type: 'link', id: 'Object Exporter', emoji: '🗂️', isVisible: true, level: 0, role: 'Donegeon Master', termKey: 'link_object_exporter' },
            { type: 'link', id: 'Asset Manager', emoji: '🖼️', isVisible: true, level: 0, role: 'Donegeon Master', termKey: 'link_asset_manager' },
            { type: 'link', id: 'Asset Library', emoji: '📚', isVisible: true, level: 0, role: 'Donegeon Master', termKey: 'link_asset_library' },
            { type: 'link', id: 'Backup & Import', emoji: '💾', isVisible: true, level: 0, role: 'Donegeon Master', termKey: 'link_backup_import' },
        ]
    }
};

module.exports = { INITIAL_SETTINGS };
