# .github/workflows/docker-build.yml

# Gives the workflow a name, which is displayed in the "Actions" tab of your GitHub repository.
name: Docker Build and Push

# Specifies the trigger for this workflow. In this case, it runs on every 'push' to the 'main' branch.
on:
  push:
    branches: [ "master", "dev"  ]

# Defines the jobs that will run as part of the workflow.
jobs:
  # This workflow contains a single job called "build-and-push".
  build-and-push:
    # Specifies the type of virtual machine to run the job on. 'ubuntu-latest' is a standard, reliable choice.
    runs-on: ubuntu-latest

    # A job is a sequence of steps. The virtual machine executes these steps in order.
    steps:
      # Step 1: Check out your repository code
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      # This uses an official action from Docker to securely log in to the Docker Hub container registry.
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          # The username for Docker Hub. We use a secret to avoid hardcoding it in the file.
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # The password or access token for Docker Hub, also stored securely as a secret.
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and push the Frontend Docker image
      # This is the core step for the frontend service. It builds the image and pushes it to Docker Hub.
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # 'context' tells Docker where to find the files for the build, including the Dockerfile.
          context: .
          # 'file' explicitly specifies the path to the Dockerfile.
          file: ./Dockerfile
          # 'push: true' tells the action to push the image to the registry after a successful build.
          push: true
          # 'tags' defines the name and tag for the Docker image.
          # It uses your Docker Hub username from secrets to create a tag like 'your-username/task-donegeon-frontend:latest'.
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-donegeon:latest
          cache-from: type=registry,ref={{ secrets.DOCKERHUB_USERNAME }}/task-donegeon:cache
          cache-to: type=registry,ref={{ secrets.DOCKERHUB_USERNAME }}/task-donegeon:cache,mode=max